imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


fos_rest:
    disable_csrf_role: ROLE_API
    allowed_methods_listener: true
    view:
        mime_types:
            json:
                - 'application/json'
                - 'application/json;version=1.0'
                - 'application/json;version=1.1'
    format_listener:
        rules:
              -
                  path: ^/api
                  priorities: [ html, json, xml ]
                  fallback_format: ~
                  prefer_extension: true
        media_type:
            version_regex: '/(v|version)=(?P<version>[0-9\.]+)/'

tbbc_rest_util:
    error:
        use_bundled_factories: true
#        exception_mapping:
#            FormErrorException:
#                class: "Tbbc\\RestUtilBundle\\Error\\Exception\\FormErrorException"
#                factory: tbbc_rest_util_form_error
#                http_status_code: 400
#                error_code: 400101
#                error_message: "Invalid input"
#            AccessDeniedException:
#                class: "Symfony\\Component\\Security\\Core\\AccessDeniedException"
#                factory: default
#                http_status_code: 401
#                error_code: 401001
#                error_message: "Access denied"
#            CustomException:
#                class: "My\\ApiBundle\\Exception\\CustomException"
#                factory: my_api_custom
#                http_status_code: 501
#                error_code: 501001
#            Exception:
#                class: "\\Exception"
#                factory: default
#                http_status_code: 500
#                error_code: 501203
#                error_message: "Server error"