api.default.index:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
    requirements:
        _method: GET

api.time_slot.all:
    pattern:  /timeslots.{_format}
    defaults: { _controller: ApiBundle:TimeSlot:all, _format: ~ }
    requirements:
        _method: GET

api.time_slot.new:
    pattern:  /timeslots/new.{_format}
    defaults: { _controller: ApiBundle:TimeSlot:newTimeSlot, _format: ~ }
    requirements:
        _method: GET

api.time_slot.post:
    pattern:  /timeslots.{_format}
    defaults: { _controller: ApiBundle:TimeSlot:postTimeSlot, _format: ~ }
    requirements:
        _method: POST

api.time_slot.delete:
    pattern:  /timeslots/{id}.{_format}
    defaults: { _controller: ApiBundle:TimeSlot:deleteTimeSlot, _format: ~ }
    requirements:
        _method: DELETE

