api.default.index:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }
    requirements:
        _method: GET

api.time_slot.all:
    pattern:  /timeslots.{_format}
    defaults: { _controller: ApiBundle:TimeSlot:all, _format: ~ }
    requirements:
        _method: GET